language: minimal
sudo: required
services:
  - docker

before_install:
  - docker build -t trahomoto/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run trahomoto/client-test npm run test -- --coverage

after_success:
  - docker build -t trahomoto/complex-docker-app-client ./client
  - docker build -t trahomoto/complex-docker-app-nginx ./nginx
  - docker build -t trahomoto/complex-docker-app-server ./server
  - docker build -t trahomoto/complex-docker-app-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push trahomoto/complex-docker-app-client
  - docker push trahomoto/complex-docker-app-nginx
  - docker push trahomoto/complex-docker-app-server
  - docker push trahomoto/complex-docker-app-worker

#deploy:
#  provider: "elasticbeanstalk"
#  region: "us-east-2"
#  app: "complex-docker-app"
#  env: "ComplexDockerApp-env"
#  bucket_name: "elasticbeanstalk-us-east-2-222263910670"
#  bucket_path: "complex-docker-app"
#  on:
#    branch: "master"
#  access_key_id: "$AWS_ACCESS_KEY"
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"