apiVersion: v1
kind: Pod
metadata:
  name: client-pad
  labels:
    component: web
spec:
  containers:
    - name: client
      image: trahomoto/complex-docker-app-client
      ports:
        - containerPort: 3000